ALTER TABLE `users` ADD COLUMN `U_round` INT(11) NOT NULL DEFAULT 1;

CREATE TABLE `rounds` (
	`R_id` INT(11) AUTO_INCREMENT, 
	`R_name` VARCHAR(128), 
	`R_start` INT(11), 
	`R_end` INT(11), 
	PRIMARY KEY(`R_id`)
);

INSERT INTO `rounds` VALUES (NULL, "Round 1", UNIX_TIMESTAMP() - UNIX_TIMESTAMP() % 86400, UNIX_TIMESTAMP() - UNIX_TIMESTAMP() % 86400 + (60 * 86400));